#!/usr/bin/env node
// Prints the README keybindings table from package.json `contributes.keybindings` (+ command titles).
//   node product/tools/keybindings-table.mjs            # print
//   node product/tools/keybindings-table.mjs --write    # refresh the table in README.md
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const titles = new Map(pkg.contributes.commands.map((c) => [c.command, c.title]));

// Built-in VS Code commands the extension rebinds (Cursor's Ctrl+R chords replace VS Code's Ctrl+K chords).
const builtin = {
  'workbench.action.openGlobalKeybindings': 'Keyboard shortcuts',
  'workbench.action.files.openFolder': 'Open folder',
  'workbench.action.selectTheme': 'Color theme',
  'workbench.action.closeAllEditors': 'Close all editors',
  'workbench.action.toggleZenMode': 'Zen mode',
  'editor.action.addCommentLine': 'Add line comment',
  'editor.action.removeCommentLine': 'Remove line comment',
  'editor.action.formatDocument': 'Format document',
  'workbench.action.keepEditor': 'Keep editor (un-preview)',
  'editor.foldAll': 'Fold all',
  'editor.unfoldAll': 'Unfold all',
};

const groups = [
  ['Chat', /^klammr\.chat\./],
  ['Agent edits', /^klammr\.edits\./],
  ['Inline edit (Ctrl+K)', /^klammr\.inlineEdit\./],
  ['Terminal', /^klammr\.terminal\./],
  ['Tab completions', /^klammr\.tab\./],
  ['Settings', /^klammr\.settings\./],
  ['Cursor-style chords (VS Code built-ins)', /^(workbench|editor)\./],
];

const prettyKey = (k) =>
  k
    .split(' ')
    .map((chord) =>
      chord
        .split('+')
        .map((p) => ({ ctrl: 'Ctrl', shift: 'Shift', alt: 'Alt', escape: 'Esc', enter: 'Enter', backspace: 'Backspace', '\\': '\\' }[p] ?? (p.length === 1 ? p.toUpperCase() : p[0].toUpperCase() + p.slice(1))))
        .join('+'),
    )
    .join(' ');

const prettyWhen = (w = '') =>
  w
    .replace(/focusedView == klammr\.chat/g, 'chat focused')
    .replace(/editorTextFocus/g, 'editor')
    .replace(/terminalFocus/g, 'terminal')
    .replace(/klammr\.inlineDiffVisible/g, 'inline diff shown')
    .replace(/klammr\.hasPendingEdits/g, 'pending agent edits')
    .replace(/klammr\.chatRunning/g, 'generating')
    .replace(/klammr\.inlineEditInputFocus && inQuickOpen/g, 'Ctrl+K prompt open')
    .replace(/klammr\.inlineEditRunning/g, 'inline edit running')
    .replace(/!editorReadonly/g, 'writable')
    .replace(/openFolderWorkspaceSupport/g, '')
    .replace(/!isAuxiliaryWindowFocusedContext/g, '')
    .replace(/editorHasDocumentFormattingProvider && /g, '')
    .replace(/foldingEnabled/g, '')
    .replace(/klammr\.inlineEditInputFocus/g, 'Ctrl+K prompt open')
    .replace(/!terminal/g, 'not in terminal')
    .replace(/!editor/g, 'not in editor')
    .replace(/!generating/g, 'idle')
    .replace(/!inline diff shown/g, 'no inline diff')
    .replace(/!Ctrl\+K prompt open/g, 'Ctrl+K prompt closed')
    .replace(/&&/g, '·')
    .replace(/\s*·\s*$/g, '')
    .replace(/^\s*·\s*/g, '')
    .trim();

const seen = new Map();
for (const kb of pkg.contributes.keybindings) {
  const label = titles.get(kb.command) ?? builtin[kb.command] ?? kb.command;
  const extra = kb.args?.action ? ` (${kb.args.action})` : '';
  const key = `${kb.command}${extra}`;
  const row = seen.get(key) ?? { command: kb.command, label: label.replace(/ \(Ctrl\+K\)$/, '') + extra, keys: [], whens: [] };
  row.keys.push(prettyKey(kb.key));
  row.whens.push(prettyWhen(kb.when));
  seen.set(key, row);
}

let out = '';
for (const [name, re] of groups) {
  const rows = [...seen.values()].filter((r) => re.test(r.command));
  if (!rows.length) continue;
  out += `\n**${name}**\n\n| Shortcut | Action | When |\n|---|---|---|\n`;
  for (const r of rows) {
    const keys = [...new Set(r.keys)].map((k) => `\`${k}\``).join(' / ');
    const whens = [...new Set(r.whens.filter(Boolean))].join('; ');
    out += `| ${keys} | ${r.label} | ${whens} |\n`;
  }
}
out = out.trimStart();
if (process.argv.includes('--write')) {
  // Refresh README.md between the markers.
  const { writeFileSync } = await import('node:fs');
  const readme = join(root, 'README.md');
  const text = readFileSync(readme, 'utf8');
  const begin = '<!-- KEYBINDINGS:BEGIN (generated by product/tools/keybindings-table.mjs --write) -->';
  const end = '<!-- KEYBINDINGS:END -->';
  const a = text.indexOf(begin), b = text.indexOf(end);
  if (a < 0 || b < 0 || b < a) throw new Error('README.md: keybindings markers not found');
  writeFileSync(readme, text.slice(0, a + begin.length) + '\n' + out + text.slice(b));
  console.error('README.md keybindings table updated');
} else {
  process.stdout.write(out);
}
