# shellcheck shell=bash
# Kursor product scripts — command wrapper, desktop entries, icons, MIME type, seeded user files, extension.
# Sourced by product/install.sh (needs common.sh, PRODUCT_DIR).

# ~/.local/bin/kursor: reads ~/.config/kursor-flags.conf, adds Wayland flags under a Wayland session,
# then execs the rebranded VSCodium CLI launcher (which handles --version, --install-extension, … headlessly).
install_wrapper() {
  mkdir -p -- "$KURSOR_BIN_DIR"
  local tmp="$KURSOR_WRAPPER.tmp.$$"
  cat >"$tmp" <<WRAP
#!/usr/bin/env bash
# Kursor launcher — generated by product/install.sh (re-running the installer rewrites this file).
# Put extra Chromium/Electron flags, one per line, in \${XDG_CONFIG_HOME:-~/.config}/kursor-flags.conf.
set -u
KURSOR_HOME="$KURSOR_OPT_DIR"
flags_file="\${XDG_CONFIG_HOME:-\$HOME/.config}/kursor-flags.conf"
flags=()
if [[ -f \$flags_file ]]; then
  while IFS= read -r line || [[ -n \$line ]]; do
    line=\${line%%#*}
    line="\${line#"\${line%%[![:space:]]*}"}"
    line="\${line%"\${line##*[![:space:]]}"}"
    [[ -n \$line ]] && flags+=("\$line")
  done <"\$flags_file"
fi
# Native Wayland (Hyprland) unless the flags file already chooses a platform.
if [[ -n \${WAYLAND_DISPLAY:-} ]]; then
  case " \${flags[*]-} " in
    *" --ozone-platform"*) ;;
    *) flags+=(--ozone-platform=wayland --enable-wayland-ime) ;;
  esac
fi
# Headless CLI invocations never open a window: pass them through without GUI flags.
for arg in "\$@"; do
  case \$arg in
    -v | --version | -h | --help | --status | --list-extensions | --install-extension | --uninstall-extension | \
      --update-extensions | --locate-shell-integration-path | --locate-extension | tunnel | serve-web)
      flags=()
      break
      ;;
  esac
done
exec "\$KURSOR_HOME/bin/kursor" "\$@" \${flags[@]+"\${flags[@]}"}
WRAP
  chmod 755 -- "$tmp" && mv -- "$tmp" "$KURSOR_WRAPPER"
  ok "wrote $KURSOR_WRAPPER"
  path_has_dir "$KURSOR_BIN_DIR" || warn "$KURSOR_BIN_DIR is not in your PATH for this shell — the launcher and Omarchy still find it, but add it to run 'kursor' here"
}

install_flags_file() { install_if_missing "$PRODUCT_DIR/defaults/kursor-flags.conf" "$KURSOR_FLAGS_FILE"; }

# hicolor icons: PNG sizes shipped in product/icons plus the scalable SVG.
install_icons() {
  local size src n=0
  for size in 16 24 32 48 64 128 256 512; do
    src="$PRODUCT_DIR/icons/kursor-$size.png"
    [[ -f $src ]] || continue
    install -Dm644 -- "$src" "$KURSOR_ICON_DIR/${size}x${size}/apps/kursor.png"
    n=$((n + 1))
  done
  install -Dm644 -- "$REPO_DIR/media/kursor.svg" "$KURSOR_ICON_DIR/scalable/apps/kursor.svg"
  touch -- "$KURSOR_ICON_DIR"   # a changed mtime makes GTK rescan the theme directory
  # A cache is only valid (and only used) when the directory carries an index.theme; otherwise icons are found by scanning.
  if [[ -f $KURSOR_ICON_DIR/index.theme ]] && have gtk-update-icon-cache; then
    gtk-update-icon-cache -q -t -f -- "$KURSOR_ICON_DIR" || warn "gtk-update-icon-cache failed (icons still work)"
  fi
  ok "installed $n PNG sizes + SVG into $KURSOR_ICON_DIR"
}

install_desktop_entries() {
  mkdir -p -- "$KURSOR_APPS_DIR"
  local exe tmp
  exe=$(desktop_quote "$KURSOR_WRAPPER")

  tmp="$KURSOR_APPS_DIR/kursor.desktop.tmp.$$"
  cat >"$tmp" <<DESK
[Desktop Entry]
Name=Kursor
Comment=AI code editor powered by the Claude Code CLI installed on your machine
GenericName=Text Editor
Exec=$exe %F
Icon=kursor
Type=Application
StartupNotify=false
StartupWMClass=kursor
Categories=TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-kursor-workspace;
Actions=new-empty-window;
Keywords=kursor;cursor;vscode;code;editor;ai;agent;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=$exe --new-window %F
Icon=kursor
DESK
  mv -- "$tmp" "$KURSOR_APPS_DIR/kursor.desktop"

  tmp="$KURSOR_APPS_DIR/kursor-url-handler.desktop.tmp.$$"
  cat >"$tmp" <<DESK
[Desktop Entry]
Name=Kursor - URL Handler
Comment=AI code editor powered by the Claude Code CLI installed on your machine
GenericName=Text Editor
Exec=$exe --open-url %U
Icon=kursor
Type=Application
NoDisplay=true
StartupNotify=true
StartupWMClass=kursor
Categories=TextEditor;Development;IDE;
MimeType=x-scheme-handler/kursor;
Keywords=kursor;
DESK
  mv -- "$tmp" "$KURSOR_APPS_DIR/kursor-url-handler.desktop"

  if have desktop-file-validate; then
    desktop-file-validate "$KURSOR_APPS_DIR/kursor.desktop" "$KURSOR_APPS_DIR/kursor-url-handler.desktop" \
      || warn "desktop-file-validate reported problems (see above)"
  fi
  have update-desktop-database && update-desktop-database -q -- "$KURSOR_APPS_DIR" 2>/dev/null || true
  ok "wrote kursor.desktop and kursor-url-handler.desktop in $KURSOR_APPS_DIR"
}

# Our own MIME type for *.code-workspace (weight below VS Code's own definition so it never wins over it)
# and the kursor:// URL scheme; both default to Kursor. No other association is touched.
install_mime() {
  install -d -- "$KURSOR_MIME_DIR/packages"
  cat >"$KURSOR_MIME_DIR/packages/kursor.xml" <<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-kursor-workspace">
    <comment>Kursor Workspace</comment>
    <sub-class-of type="application/json"/>
    <glob pattern="*.code-workspace" weight="40"/>
  </mime-type>
</mime-info>
XML
  if have update-mime-database; then
    update-mime-database -- "$KURSOR_MIME_DIR" >/dev/null 2>&1 || warn "update-mime-database failed"
  fi
  if have xdg-mime; then
    xdg-mime default kursor.desktop x-scheme-handler/kursor application/x-kursor-workspace 2>/dev/null \
      || warn "xdg-mime default failed (kursor:// links will not open automatically)"
  fi
  ok "registered application/x-kursor-workspace and x-scheme-handler/kursor"
}

seed_user_files() {
  install_if_missing "$PRODUCT_DIR/defaults/argv.json" "$KURSOR_DATA_DIR/argv.json"
  install_if_missing "$PRODUCT_DIR/defaults/settings.json" "$KURSOR_USER_DIR/settings.json"
  install_if_missing "$PRODUCT_DIR/defaults/keybindings.json" "$KURSOR_USER_DIR/keybindings.json"
}

# Headless: bin/kursor runs cli.js under ELECTRON_RUN_AS_NODE, no window is opened.
install_kursor_extension() {
  local vsix=$1 out
  info "installing $(basename -- "$vsix") into $KURSOR_DATA_DIR/extensions"
  if out=$("$KURSOR_OPT_DIR/bin/kursor" --install-extension "$vsix" --force 2>&1); then
    ok "$(printf '%s\n' "$out" | sed -e '/^[[:space:]]*$/d' | tail -n 1)"
  else
    printf '%s\n' "$out" >&2
    die "extension install failed. Retry by hand: \"$KURSOR_OPT_DIR/bin/kursor\" --install-extension \"$vsix\" --force"
  fi
}

# settings_set_if_absent <key> <json-value> — add one key to the (JSONC) settings.json without rewriting
# the rest of the file; keys the user already has are left exactly as they are.
settings_set_if_absent() {
  local key=$1 value=$2 f="$KURSOR_USER_DIR/settings.json"
  mkdir -p -- "$KURSOR_USER_DIR"
  [[ -f $f ]] || printf '{\n}\n' >"$f"
  if grep -q -- "\"$key\"" "$f"; then
    info "settings.json already sets $key — left unchanged"
    return 0
  fi
  sed -i -E "0,/\{/{s/\{/{\n  \"$key\": $value,/}" "$f"
  ok "set $key = $value in $f"
}

install_icon_theme() {
  local id="PKief.material-icon-theme"
  # --list-extensions prints ids lower-cased.
  if "$KURSOR_OPT_DIR/bin/kursor" --list-extensions 2>/dev/null | grep -Fxiq -- "$id"; then
    ok "$id already installed"
  elif "$KURSOR_OPT_DIR/bin/kursor" --install-extension "$id" >/dev/null 2>&1; then
    ok "installed $id from Open VSX"
  else
    warn "could not install $id from Open VSX (offline?) — skipping the icon theme"
    return 0
  fi
  settings_set_if_absent "workbench.iconTheme" '"material-icon-theme"'
}
