// Klammr product scripts — Linux desktop integration (+ Omarchy/Hyprland extras) and its removal.
// ~/.local/bin/klammr wrapper, .desktop entries, hicolor icons, MIME type, flags file;
// Omarchy: theme hook via `omarchy hook install`, SUPER + SHIFT + K binding, default editor.
// Everything is user-scoped; nothing under /usr is touched and sudo is never used.

import fs from 'node:fs';
import path from 'node:path';
import {
  HYPR_BIND_LINE, HYPR_BIND_MARKER, PRODUCT_DIR, confirm, desktopQuote, die, ensureDir, exists, have, isFile, isDir,
  log, removePath, run, writeFileAtomic, writeIfMissing,
} from './common.mjs';

export const omarchyAvailable = () => !!have('omarchy');

const WRAPPER = (appRoot) => `#!/usr/bin/env bash
# Klammr launcher — generated by product/install.mjs (re-running the installer rewrites this file).
# Put extra Chromium/Electron flags, one per line, in \${XDG_CONFIG_HOME:-~/.config}/klammr-flags.conf.
set -u
KLAMMR_HOME="${appRoot}"
flags_file="\${XDG_CONFIG_HOME:-\$HOME/.config}/klammr-flags.conf"
flags=()
if [[ -f \$flags_file ]]; then
  while IFS= read -r line || [[ -n \$line ]]; do
    line=\${line%%#*}
    line="\${line#"\${line%%[![:space:]]*}"}"
    line="\${line%"\${line##*[![:space:]]}"}"
    [[ -n \$line ]] && flags+=("\$line")
  done <"\$flags_file"
fi
# Native Wayland (Hyprland) unless the flags file already chooses a platform.
if [[ -n \${WAYLAND_DISPLAY:-} ]]; then
  case " \${flags[*]-} " in
    *" --ozone-platform"*) ;;
    *) flags+=(--ozone-platform=wayland --enable-wayland-ime) ;;
  esac
fi
# Headless CLI invocations never open a window: pass them through without GUI flags.
for arg in "\$@"; do
  case \$arg in
    -v | --version | -h | --help | --status | --list-extensions | --install-extension | --uninstall-extension | \\
      --update-extensions | --locate-shell-integration-path | --locate-extension | tunnel | serve-web)
      flags=()
      break
      ;;
  esac
done
exec "\$KLAMMR_HOME/bin/klammr" "\$@" \${flags[@]+"\${flags[@]}"}
`;

export function installWrapper(paths) {
  writeFileAtomic(paths.wrapper, WRAPPER(paths.appRoot), 0o755);
  log.ok(`wrote ${paths.wrapper}`);
  const onPath = (process.env.PATH || '').split(':').includes(paths.binDir);
  if (!onPath) log.warn(`${paths.binDir} is not in your PATH for this shell — the launcher and Omarchy still find it, but add it to run 'klammr' here`);
}

export function installFlagsFile(paths) {
  writeIfMissing(paths.flagsFile, fs.readFileSync(path.join(PRODUCT_DIR, 'defaults', 'klammr-flags.conf')));
}

// hicolor icons: PNG sizes shipped in product/icons plus the scalable SVG (bundles carry icons/klammr.svg).
export function installIcons(paths) {
  let n = 0;
  for (const size of [16, 24, 32, 48, 64, 128, 256, 512]) {
    const src = path.join(PRODUCT_DIR, 'icons', `klammr-${size}.png`);
    if (!isFile(src)) continue;
    const dest = path.join(paths.iconDir, `${size}x${size}`, 'apps', 'klammr.png');
    ensureDir(path.dirname(dest));
    fs.copyFileSync(src, dest);
    n++;
  }
  const svg = [path.join(PRODUCT_DIR, 'icons', 'klammr.svg'), path.join(PRODUCT_DIR, '..', 'media', 'klammr.svg')].find(isFile);
  if (svg) {
    const dest = path.join(paths.iconDir, 'scalable', 'apps', 'klammr.svg');
    ensureDir(path.dirname(dest));
    fs.copyFileSync(svg, dest);
  }
  const now = new Date();
  try { fs.utimesSync(paths.iconDir, now, now); } catch { /* a changed mtime makes GTK rescan; best effort */ }
  // A cache is only valid (and only used) when the directory carries an index.theme.
  if (isFile(path.join(paths.iconDir, 'index.theme')) && have('gtk-update-icon-cache')) {
    if (!run('gtk-update-icon-cache', ['-q', '-t', '-f', '--', paths.iconDir]).ok) log.warn('gtk-update-icon-cache failed (icons still work)');
  }
  log.ok(`installed ${n} PNG sizes${svg ? ' + SVG' : ''} into ${paths.iconDir}`);
}

export function installDesktopEntries(paths) {
  ensureDir(paths.appsDir);
  const exe = desktopQuote(paths.wrapper);
  writeFileAtomic(path.join(paths.appsDir, 'klammr.desktop'), `[Desktop Entry]
Name=Klammr
Comment=AI code editor powered by the Claude Code CLI installed on your machine
GenericName=Text Editor
Exec=${exe} %F
Icon=klammr
Type=Application
StartupNotify=false
StartupWMClass=klammr
Categories=TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-klammr-workspace;
Actions=new-empty-window;
Keywords=klammr;cursor;vscode;code;editor;ai;agent;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=${exe} --new-window %F
Icon=klammr
`, 0o644);
  writeFileAtomic(path.join(paths.appsDir, 'klammr-url-handler.desktop'), `[Desktop Entry]
Name=Klammr - URL Handler
Comment=AI code editor powered by the Claude Code CLI installed on your machine
GenericName=Text Editor
Exec=${exe} --open-url %U
Icon=klammr
Type=Application
NoDisplay=true
StartupNotify=true
StartupWMClass=klammr
Categories=TextEditor;Development;IDE;
MimeType=x-scheme-handler/klammr;
Keywords=klammr;
`, 0o644);
  if (have('desktop-file-validate')) {
    const r = run('desktop-file-validate', [path.join(paths.appsDir, 'klammr.desktop'), path.join(paths.appsDir, 'klammr-url-handler.desktop')]);
    if (!r.ok) log.warn(`desktop-file-validate reported problems:\n${r.stdout}${r.stderr}`);
  }
  if (have('update-desktop-database')) run('update-desktop-database', ['-q', '--', paths.appsDir]);
  log.ok(`wrote klammr.desktop and klammr-url-handler.desktop in ${paths.appsDir}`);
}

// Our own MIME type for *.code-workspace (weight below VS Code's own definition so it never wins over it)
// and the klammr:// URL scheme; both default to Klammr. No other association is touched.
export function installMime(paths) {
  const pkg = path.join(paths.mimeDir, 'packages', 'klammr.xml');
  writeFileAtomic(pkg, `<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-klammr-workspace">
    <comment>Klammr Workspace</comment>
    <sub-class-of type="application/json"/>
    <glob pattern="*.code-workspace" weight="40"/>
  </mime-type>
</mime-info>
`, 0o644);
  if (have('update-mime-database') && !run('update-mime-database', ['--', paths.mimeDir]).ok) log.warn('update-mime-database failed');
  if (have('xdg-mime') && !run('xdg-mime', ['default', 'klammr.desktop', 'x-scheme-handler/klammr', 'application/x-klammr-workspace']).ok) {
    log.warn('xdg-mime default failed (klammr:// links will not open automatically)');
  }
  log.ok('registered application/x-klammr-workspace and x-scheme-handler/klammr');
}

export function klammrRunning(paths) {
  return have('pgrep') && run('pgrep', ['-f', '--', `${paths.appRoot}/klammr`]).ok;
}

// ---- Omarchy / Hyprland -----------------------------------------------------------------------
export function omarchyInstallThemeHook(paths) {
  const hook = path.join(PRODUCT_DIR, 'omarchy', 'klammr-theme.hook');
  const r = run('omarchy', ['hook', 'install', 'theme-set', hook]);
  if (!r.ok) die(`'omarchy hook install theme-set' failed:\n${r.stderr || r.stdout}`);
  try { fs.accessSync(paths.omarchy.hookFile, fs.constants.X_OK); } catch { die(`hook was not installed at ${paths.omarchy.hookFile}`); }
  log.ok(`installed theme hook ${paths.omarchy.hookFile}`);
}

// Apply the current Omarchy theme to Klammr right away (the hook otherwise runs on the next `omarchy theme set`).
export function omarchyRunThemeHookOnce(paths) {
  let theme = '';
  if (have('omarchy-theme-current')) {
    theme = run('omarchy-theme-current').stdout.trim().toLowerCase().replace(/ /g, '-');
    if (theme === 'unknown') theme = '';
  }
  const r = run('bash', [paths.omarchy.hookFile, theme], { env: { ...process.env, PATH: `${paths.binDir}:${process.env.PATH || ''}` } });
  if (!r.ok) { log.warn('theme hook reported an error — Klammr Dark stays active'); return; }
  if (exists(paths.omarchy.skipToggle)) log.info(`theme hook is opted out (${paths.omarchy.skipToggle} exists) — Klammr Dark stays`);
  else log.ok(`applied the current Omarchy theme${theme ? ` (${theme})` : ''} to Klammr`);
}

function hyprReload() {
  if (!process.env.HYPRLAND_INSTANCE_SIGNATURE || !have('hyprctl')) {
    log.info('no running Hyprland session detected; the binding is active after the next reload/login');
    return;
  }
  if (!run('hyprctl', ['reload']).ok) { log.warn('hyprctl reload failed — reload Hyprland by hand'); return; }
  const errs = run('hyprctl', ['configerrors']).stdout;
  if (errs.trim()) { log.warn('hyprctl configerrors:'); console.error(errs); } else log.ok('Hyprland reloaded; hyprctl configerrors reports none');
}

export function installHyprBind(paths) {
  const f = paths.omarchy.hyprBindings;
  ensureDir(path.dirname(f));
  if (!exists(f)) fs.writeFileSync(f, '');
  const text = fs.readFileSync(f, 'utf8');
  if (text.includes(HYPR_BIND_MARKER)) {
    log.ok(`SUPER + SHIFT + K → Klammr already present in ${f}`);
  } else if (text.includes('"SUPER + SHIFT + K"')) {
    log.warn(`${f} already binds SUPER + SHIFT + K to something else — left untouched.`);
    log.warn(`To bind Klammr yourself add:  ${HYPR_BIND_LINE}`);
    return;
  } else {
    fs.appendFileSync(f, `${text && !text.endsWith('\n') ? '\n' : ''}${HYPR_BIND_LINE}\n`);
    log.ok(`appended SUPER + SHIFT + K → Klammr to ${f}`);
  }
  hyprReload();
}

export function removeHyprBind(paths) {
  const f = paths.omarchy.hyprBindings;
  if (!isFile(f)) return;
  const text = fs.readFileSync(f, 'utf8');
  if (!text.includes(HYPR_BIND_MARKER)) return;
  writeFileAtomic(f, text.split('\n').filter((l) => !l.includes(HYPR_BIND_MARKER)).join('\n'));
  log.ok(`removed the SUPER + SHIFT + K binding from ${f}`);
  hyprReload();
}

export function setDefaultEditor(paths) {
  writeFileAtomic(paths.omarchy.defaultEditorFile, 'klammr\n', 0o644);
  log.ok('Omarchy default editor → klammr (SUPER + SHIFT + N, omarchy-launch-editor, $EDITOR in GUI apps)');
}

export function unsetDefaultEditor(paths) {
  const f = paths.omarchy.defaultEditorFile;
  if (isFile(f) && fs.readFileSync(f, 'utf8').trim() === 'klammr') {
    fs.unlinkSync(f);
    log.ok("Omarchy default editor reset (was klammr; Omarchy falls back to nvim — run 'omarchy default editor <name>' to pick another)");
  }
}

// ---- uninstall --------------------------------------------------------------------------------
export function uninstallLinux(paths, { yes, keepConfig, purge }) {
  log.step('Removing Klammr');
  if (klammrRunning(paths)) log.warn('Klammr appears to be running — close it first; the running instance keeps working until then');

  const parent = path.dirname(paths.appRoot);
  const base = path.basename(paths.appRoot);
  if (isDir(parent)) {
    for (const name of fs.readdirSync(parent)) {
      if (name === base || name.startsWith(`${base}.staging.`) || name.startsWith(`${base}.old.`)) removePath(path.join(parent, name));
    }
  }
  removePath(paths.wrapper);

  let removed = false;
  for (const f of ['klammr.desktop', 'klammr-url-handler.desktop']) {
    const p = path.join(paths.appsDir, f);
    if (isFile(p)) { fs.unlinkSync(p); removed = true; }
  }
  if (removed) {
    if (have('update-desktop-database')) run('update-desktop-database', ['-q', '--', paths.appsDir]);
    log.ok(`removed desktop entries from ${paths.appsDir}`);
  }

  removed = false;
  if (isDir(paths.iconDir)) {
    for (const size of fs.readdirSync(paths.iconDir)) {
      for (const name of ['klammr.png', 'klammr.svg']) {
        const p = path.join(paths.iconDir, size, 'apps', name);
        if (isFile(p)) { fs.unlinkSync(p); removed = true; }
      }
    }
  }
  if (removed) {
    const now = new Date();
    try { fs.utimesSync(paths.iconDir, now, now); } catch { /* best effort */ }
    if (isFile(path.join(paths.iconDir, 'index.theme')) && have('gtk-update-icon-cache')) run('gtk-update-icon-cache', ['-q', '-t', '-f', '--', paths.iconDir]);
    log.ok(`removed icons from ${paths.iconDir}`);
  }

  const mimePkg = path.join(paths.mimeDir, 'packages', 'klammr.xml');
  if (isFile(mimePkg)) {
    fs.unlinkSync(mimePkg);
    if (have('update-mime-database')) run('update-mime-database', ['--', paths.mimeDir]);
    log.ok('removed MIME type application/x-klammr-workspace');
  }
  if (isFile(paths.mimeapps)) {
    const lines = fs.readFileSync(paths.mimeapps, 'utf8').split('\n');
    const kept = lines.filter((l) => !/^(x-scheme-handler\/klammr|application\/x-klammr-workspace)=/.test(l));
    if (kept.length !== lines.length) { writeFileAtomic(paths.mimeapps, kept.join('\n')); log.ok(`removed klammr defaults from ${paths.mimeapps}`); }
  }

  removePath(paths.omarchy.hookFile, 'Omarchy theme hook');
  removeHyprBind(paths);
  unsetDefaultEditor(paths);

  log.step('User data');
  if (keepConfig) {
    log.info(`kept ${paths.configRoot}, ${paths.dataDir} and ${paths.flagsFile} (--keep-config)`);
  } else {
    if (!process.stdin.isTTY && !yes) log.info('no terminal to ask on — keeping settings, extensions and flags (use --yes to delete, --keep-config to silence this)');
    const ask = (p, what) => {
      if (!exists(p)) return;
      if (confirm(`Delete ${p} (${what})?`, false, yes)) removePath(p); else log.info(`kept ${p}`);
    };
    ask(paths.configRoot, 'settings, keybindings, window state, workspace storage');
    ask(paths.dataDir, 'installed extensions, argv.json');
    ask(paths.flagsFile, 'launcher flags');
  }
  if (purge) removePath(paths.cacheDir, `cached download ${paths.cacheDir}`);
  else if (isDir(paths.cacheDir)) log.info(`kept the cached VSCodium download in ${paths.cacheDir} (pass --purge to delete it)`);
}

