// Generates media/themes/klammr-dark.json from the brand palette in docs/BRAND.md.
//
//   npm run theme                          write the theme
//   node scripts/build-theme.mjs --check   exit 1 when the committed theme is out of date (CI)
//
// Every colour below is a brand token, a lightness step of one, or one of them with alpha. The layout is
// built for VS Code's Modern UI (floating cards): Ink is the window around the cards, Surface the cards,
// fields are inset in Ink and overlays (menus, widgets, quick input) float a step above Surface.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'media', 'themes', 'klammr-dark.json');

// ---- Brand tokens (docs/BRAND.md) -----------------------------------------------------------
const brand = {
  ink: '#0F1014',
  surface: '#1A1D25',
  border: '#262A35',
  mist: '#EEF0F6',
  muted: '#8B91A1',
  violet: '#7C8CFF',
  violetHover: '#8F9BFF',
  orchid: '#B57CFF',
  keep: '#5FD38A',
  undo: '#FF6B78',
  warn: '#E8A33D',
};

// ---- Interface steps -------------------------------------------------------------------------
const ui = {
  window: brand.ink, // title bar, status bar, the gaps between cards
  card: brand.surface, // editor, side bars, panel
  field: brand.ink, // inputs, dropdowns, terminal-style wells
  raised: '#222631', // menus, widgets, quick input, notifications
  raisedHover: '#2A2E3B',
  line: brand.border, // hairlines
  lineStrong: '#353A48', // field borders, active guides
  text: '#CDD1DC', // body text
  bright: brand.mist, // headings, active and selected items
  muted: brand.muted, // secondary text, inactive items
  faint: '#5F6578', // line numbers, disabled, placeholders
  icon: '#A3A9B8',
};

// ---- Syntax: the accents lightened for text, plus one sky hue for types ------------------------
const syntax = {
  comment: '#6E768A',
  keyword: '#C99BFF', // orchid
  func: brand.violetHover, // violet
  string: '#8BDFA9', // keep
  number: '#EEBA6D', // warn
  type: '#79CFEC', // sky
  tag: '#FF8F9A', // undo
  text: ui.text,
  operator: brand.muted,
};

/** `hex` with an alpha channel (0–1). */
function a(hex, alpha) {
  return hex + Math.round(alpha * 255).toString(16).padStart(2, '0').toUpperCase();
}
const none = '#00000000';

const colors = {
  // ---- base
  foreground: ui.text,
  descriptionForeground: ui.muted,
  disabledForeground: ui.faint,
  errorForeground: brand.undo,
  'icon.foreground': ui.icon,
  focusBorder: brand.violet,
  'selection.background': a(brand.violet, 0.4),
  'widget.border': ui.line,
  'widget.shadow': a('#000000', 0.5),
  'sash.hoverBorder': brand.violet,
  'textLink.foreground': brand.violetHover,
  'textLink.activeForeground': '#A6AFFF',
  'textBlockQuote.background': a(ui.bright, 0.03),
  'textBlockQuote.border': ui.lineStrong,
  'textCodeBlock.background': ui.field,
  'textPreformat.foreground': ui.bright,
  'textPreformat.background': a(ui.bright, 0.07),
  'textSeparator.foreground': ui.line,
  'toolbar.hoverBackground': a(ui.bright, 0.07),
  'toolbar.activeBackground': a(ui.bright, 0.1),
  'progressBar.background': brand.violet,
  'surface.background': ui.card,
  'surface.foreground': ui.text,
  'surface.border': ui.line,
  'profiles.sashBorder': ui.line,

  // ---- window frame
  'titleBar.activeBackground': ui.window,
  'titleBar.activeForeground': ui.text,
  'titleBar.inactiveBackground': ui.window,
  'titleBar.inactiveForeground': ui.muted,
  'titleBar.border': none,
  'commandCenter.background': ui.card,
  'commandCenter.foreground': ui.muted,
  'commandCenter.activeBackground': ui.raised,
  'commandCenter.activeForeground': ui.bright,
  'commandCenter.border': ui.line,
  'commandCenter.activeBorder': ui.lineStrong,
  'commandCenter.inactiveBorder': ui.line,
  'commandCenter.inactiveForeground': ui.faint,
  'commandCenter.debuggingBackground': a(brand.orchid, 0.25),
  'menubar.selectionBackground': a(ui.bright, 0.08),
  'menubar.selectionForeground': ui.bright,
  'menu.background': ui.raised,
  'menu.foreground': ui.text,
  'menu.selectionBackground': a(brand.violet, 0.22),
  'menu.selectionForeground': ui.bright,
  'menu.separatorBackground': ui.line,
  'menu.border': ui.line,

  // ---- activity bar (side position) and its top/bottom variant inside the side bar card
  'activityBar.background': ui.window,
  'activityBar.foreground': ui.bright,
  'activityBar.inactiveForeground': ui.muted,
  'activityBar.activeBorder': brand.violet,
  'activityBar.activeBackground': a(ui.bright, 0.06),
  'activityBar.border': none,
  'activityBarBadge.background': brand.violet,
  'activityBarBadge.foreground': brand.ink,
  'activityBarTop.background': ui.card,
  'activityBarTop.foreground': ui.bright,
  'activityBarTop.inactiveForeground': ui.muted,
  'activityBarTop.activeBorder': brand.violet,
  'activityBarTop.activeBackground': a(ui.bright, 0.07),
  'activityBarTop.dropBorder': brand.violet,
  'modernActivityBar.background': ui.window,
  'modernActivityBar.inactiveBackground': ui.window,
  'modernActivityBar.activeBackground': a(ui.bright, 0.08),
  'modernActivityBar.activeForeground': ui.bright,
  'modernActivityBar.hoverBackground': a(ui.bright, 0.05),
  'modernActivityBar.hoverForeground': ui.bright,
  'badge.background': brand.violet,
  'badge.foreground': brand.ink,

  // ---- side bars (the chat lives in the secondary side bar)
  'sideBar.background': ui.card,
  'sideBar.foreground': ui.text,
  'sideBar.border': ui.line,
  'sideBar.dropBackground': a(brand.violet, 0.14),
  'sideBarTitle.foreground': ui.bright,
  'sideBarTitle.background': ui.card,
  'sideBarSectionHeader.background': ui.card,
  'sideBarSectionHeader.foreground': ui.text,
  'sideBarSectionHeader.border': ui.line,
  'sideBarActivityBarTop.border': ui.line,
  'sideBarStickyScroll.background': ui.card,
  'sideBarStickyScroll.border': ui.line,
  'sideBarStickyScroll.shadow': a('#000000', 0.3),

  // ---- lists and trees
  'list.activeSelectionBackground': a(brand.violet, 0.2),
  'list.activeSelectionForeground': ui.bright,
  'list.activeSelectionIconForeground': ui.bright,
  'list.inactiveSelectionBackground': a(ui.bright, 0.07),
  'list.inactiveSelectionForeground': ui.bright,
  'list.focusBackground': a(ui.bright, 0.07),
  'list.focusForeground': ui.bright,
  'list.focusOutline': brand.violet,
  'list.inactiveFocusOutline': none,
  'list.hoverBackground': a(ui.bright, 0.04),
  'list.hoverForeground': ui.bright,
  'list.highlightForeground': brand.violetHover,
  'list.focusHighlightForeground': brand.violetHover,
  'list.dropBackground': a(brand.violet, 0.14),
  'list.errorForeground': brand.undo,
  'list.warningForeground': brand.warn,
  'list.deemphasizedForeground': ui.faint,
  'listFilterWidget.background': ui.raised,
  'listFilterWidget.outline': none,
  'listFilterWidget.noMatchesOutline': brand.undo,
  'listFilterWidget.shadow': a('#000000', 0.4),
  'tree.indentGuidesStroke': ui.lineStrong,
  'tree.inactiveIndentGuidesStroke': a(ui.lineStrong, 0.5),
  'tree.tableColumnsBorder': ui.line,
  'tree.tableOddRowsBackground': a(ui.bright, 0.02),

  // ---- editor
  'editor.background': ui.card,
  'editor.foreground': ui.text,
  'editor.border': ui.line,
  'editorLineNumber.foreground': ui.faint,
  'editorLineNumber.activeForeground': ui.bright,
  'editorLineNumber.dimmedForeground': a(ui.faint, 0.6),
  'editorCursor.foreground': brand.orchid,
  'editorCursor.background': brand.ink,
  'editorMultiCursor.primary.foreground': brand.orchid,
  'editorMultiCursor.secondary.foreground': a(brand.orchid, 0.6),
  'editor.lineHighlightBackground': a(ui.bright, 0.03),
  'editor.lineHighlightBorder': none,
  'editor.selectionBackground': a(brand.violet, 0.3),
  'editor.inactiveSelectionBackground': a(brand.violet, 0.15),
  'editor.selectionHighlightBackground': a(brand.violet, 0.14),
  'editor.selectionHighlightBorder': none,
  'editor.wordHighlightBackground': a(ui.bright, 0.08),
  'editor.wordHighlightStrongBackground': a(brand.violet, 0.18),
  'editor.wordHighlightTextBackground': a(ui.bright, 0.08),
  'editor.findMatchBackground': a(brand.warn, 0.4),
  'editor.findMatchBorder': brand.warn,
  'editor.findMatchHighlightBackground': a(brand.warn, 0.18),
  'editor.findRangeHighlightBackground': a(ui.bright, 0.05),
  'editor.hoverHighlightBackground': a(brand.violet, 0.12),
  'editor.rangeHighlightBackground': a(ui.bright, 0.04),
  'editor.symbolHighlightBackground': a(brand.warn, 0.18),
  'editor.foldBackground': a(brand.violet, 0.08),
  'editor.foldPlaceholderForeground': ui.muted,
  'editor.linkedEditingBackground': a(brand.orchid, 0.16),
  'editor.snippetTabstopHighlightBackground': a(brand.violet, 0.16),
  'editor.snippetFinalTabstopHighlightBorder': brand.violet,
  'editorLink.activeForeground': brand.violetHover,
  'editorWhitespace.foreground': ui.lineStrong,
  'editorIndentGuide.background1': '#2A2E3A',
  'editorIndentGuide.activeBackground1': '#424859',
  'editorRuler.foreground': ui.line,
  'editorBracketMatch.background': a(brand.violet, 0.12),
  'editorBracketMatch.border': a(ui.muted, 0.6),
  'editorBracketHighlight.foreground1': '#A3A9B8',
  'editorBracketHighlight.foreground2': '#9FA8F2',
  'editorBracketHighlight.foreground3': '#C3A7EE',
  'editorBracketHighlight.foreground4': '#A3A9B8',
  'editorBracketHighlight.foreground5': '#9FA8F2',
  'editorBracketHighlight.foreground6': '#C3A7EE',
  'editorBracketHighlight.unexpectedBracket.foreground': brand.undo,
  'editorBracketPairGuide.activeBackground1': a('#9FA8F2', 0.5),
  'editorCodeLens.foreground': ui.muted,
  'editorLightBulb.foreground': brand.warn,
  'editorLightBulbAutoFix.foreground': brand.violet,
  'editorLightBulbAi.foreground': brand.orchid,
  'editorInlayHint.background': a(ui.bright, 0.05),
  'editorInlayHint.foreground': ui.muted,
  'editorInlayHint.typeBackground': a(ui.bright, 0.05),
  'editorInlayHint.typeForeground': ui.muted,
  'editorInlayHint.parameterBackground': a(ui.bright, 0.05),
  'editorInlayHint.parameterForeground': ui.muted,
  'editorGhostText.foreground': a(ui.bright, 0.36),
  'editorGhostText.border': none,
  'editorUnnecessaryCode.opacity': '#000000A0',
  'editorError.foreground': brand.undo,
  'editorWarning.foreground': brand.warn,
  'editorInfo.foreground': brand.violet,
  'editorHint.foreground': a(ui.bright, 0.6),
  'editorGutter.background': ui.card,
  'editorGutter.addedBackground': brand.keep,
  'editorGutter.modifiedBackground': brand.violet,
  'editorGutter.deletedBackground': brand.undo,
  'editorGutter.commentRangeForeground': ui.lineStrong,
  'editorGutter.foldingControlForeground': ui.muted,
  'editorOverviewRuler.border': none,
  'editorOverviewRuler.background': ui.card,
  'editorOverviewRuler.findMatchForeground': a(brand.warn, 0.6),
  'editorOverviewRuler.rangeHighlightForeground': a(brand.violet, 0.5),
  'editorOverviewRuler.selectionHighlightForeground': a(ui.bright, 0.4),
  'editorOverviewRuler.wordHighlightForeground': a(ui.bright, 0.4),
  'editorOverviewRuler.wordHighlightStrongForeground': a(brand.violet, 0.6),
  'editorOverviewRuler.modifiedForeground': a(brand.violet, 0.6),
  'editorOverviewRuler.addedForeground': a(brand.keep, 0.6),
  'editorOverviewRuler.deletedForeground': a(brand.undo, 0.6),
  'editorOverviewRuler.errorForeground': a(brand.undo, 0.8),
  'editorOverviewRuler.warningForeground': a(brand.warn, 0.8),
  'editorOverviewRuler.infoForeground': a(brand.violet, 0.8),
  'editorStickyScroll.background': ui.card,
  'editorStickyScroll.border': ui.line,
  'editorStickyScroll.shadow': a('#000000', 0.3),
  'editorStickyScrollHover.background': ui.raised,
  'editorWidget.background': ui.raised,
  'editorWidget.foreground': ui.text,
  'editorWidget.border': ui.line,
  'editorWidget.resizeBorder': brand.violet,
  'editorSuggestWidget.background': ui.raised,
  'editorSuggestWidget.border': ui.line,
  'editorSuggestWidget.foreground': ui.text,
  'editorSuggestWidget.selectedBackground': a(brand.violet, 0.22),
  'editorSuggestWidget.selectedForeground': ui.bright,
  'editorSuggestWidget.selectedIconForeground': ui.bright,
  'editorSuggestWidget.highlightForeground': brand.violetHover,
  'editorSuggestWidget.focusHighlightForeground': brand.violetHover,
  'editorSuggestWidgetStatus.foreground': ui.muted,
  'editorHoverWidget.background': ui.raised,
  'editorHoverWidget.border': ui.line,
  'editorHoverWidget.foreground': ui.text,
  'editorHoverWidget.highlightForeground': brand.violetHover,
  'editorHoverWidget.statusBarBackground': ui.raisedHover,
  'editorMarkerNavigation.background': ui.raised,
  'editorMarkerNavigationError.background': brand.undo,
  'editorMarkerNavigationError.headerBackground': a(brand.undo, 0.12),
  'editorMarkerNavigationWarning.background': brand.warn,
  'editorMarkerNavigationWarning.headerBackground': a(brand.warn, 0.12),
  'editorMarkerNavigationInfo.background': brand.violet,
  'editorMarkerNavigationInfo.headerBackground': a(brand.violet, 0.12),
  'peekView.border': brand.violet,
  'peekViewEditor.background': ui.field,
  'peekViewEditorGutter.background': ui.field,
  'peekViewEditor.matchHighlightBackground': a(brand.warn, 0.3),
  'peekViewResult.background': ui.raised,
  'peekViewResult.fileForeground': ui.bright,
  'peekViewResult.lineForeground': ui.text,
  'peekViewResult.matchHighlightBackground': a(brand.warn, 0.3),
  'peekViewResult.selectionBackground': a(brand.violet, 0.22),
  'peekViewResult.selectionForeground': ui.bright,
  'peekViewTitle.background': ui.raised,
  'peekViewTitleDescription.foreground': ui.muted,
  'peekViewTitleLabel.foreground': ui.bright,

  // ---- editor groups and tabs (classic tabs, then the Modern UI pill tabs)
  'editorGroup.border': ui.line,
  'editorGroup.dropBackground': a(brand.violet, 0.14),
  'editorGroup.dropIntoPromptBackground': ui.raised,
  'editorGroup.dropIntoPromptForeground': ui.text,
  'editorGroup.dropIntoPromptBorder': ui.line,
  'editorGroup.emptyBackground': ui.card,
  'editorGroup.focusedEmptyBorder': none,
  'editorGroupHeader.tabsBackground': ui.card,
  'editorGroupHeader.tabsBorder': ui.line,
  'editorGroupHeader.noTabsBackground': ui.card,
  'editorGroupHeader.border': ui.line,
  'editorPane.background': ui.card,
  'sideBySideEditor.horizontalBorder': ui.line,
  'sideBySideEditor.verticalBorder': ui.line,
  'tab.activeBackground': ui.card,
  'tab.activeForeground': ui.bright,
  'tab.activeBorder': brand.violet,
  'tab.activeBorderTop': none,
  'tab.selectedBorderTop': none,
  'tab.selectedBackground': a(ui.bright, 0.05),
  'tab.selectedForeground': ui.bright,
  'tab.inactiveBackground': ui.card,
  'tab.inactiveForeground': ui.muted,
  'tab.unfocusedActiveBackground': ui.card,
  'tab.unfocusedActiveForeground': ui.text,
  'tab.unfocusedActiveBorder': a(brand.violet, 0.4),
  'tab.unfocusedActiveBorderTop': none,
  'tab.unfocusedInactiveBackground': ui.card,
  'tab.unfocusedInactiveForeground': a(ui.muted, 0.8),
  'tab.hoverBackground': a(ui.bright, 0.04),
  'tab.unfocusedHoverBackground': a(ui.bright, 0.03),
  'tab.hoverForeground': ui.bright,
  'tab.unfocusedHoverForeground': ui.text,
  'tab.border': none,
  'tab.lastPinnedBorder': ui.line,
  'tab.activeModifiedBorder': brand.violet,
  'tab.inactiveModifiedBorder': a(brand.violet, 0.5),
  'tab.unfocusedActiveModifiedBorder': a(brand.violet, 0.5),
  'tab.unfocusedInactiveModifiedBorder': a(brand.violet, 0.3),
  'tab.dragAndDropBorder': brand.violet,
  'modernTab.activeBackground': a(ui.bright, 0.08),
  'modernTab.activeForeground': ui.bright,
  'modernTab.hoverBackground': a(ui.bright, 0.05),
  'modernTab.hoverForeground': ui.bright,
  'modernEditorTab.activeBackground': a(ui.bright, 0.08),
  'modernEditorTab.activeForeground': ui.bright,
  'modernEditorTab.activeHoverBackground': a(ui.bright, 0.1),
  'modernEditorTab.inactiveBackground': none,
  'modernEditorTab.hoverBackground': a(ui.bright, 0.05),
  'modernEditorTab.hoverForeground': ui.bright,
  'modernEditorTab.activeActionBackground': '#2A2D36',
  'modernEditorTab.activeHoverActionBackground': '#30333C',
  'modernEditorTab.hoverActionBackground': '#24272F',
  'modernEditorTab.selectedActionBackground': '#24272F',
  'breadcrumb.background': ui.card,
  'breadcrumb.foreground': ui.muted,
  'breadcrumb.focusForeground': ui.bright,
  'breadcrumb.activeSelectionForeground': ui.bright,
  'breadcrumbPicker.background': ui.raised,

  // ---- panel and terminal
  'panel.background': ui.card,
  'panel.border': ui.line,
  'panel.dropBorder': brand.violet,
  'panelTitle.activeBorder': brand.violet,
  'panelTitle.activeForeground': ui.bright,
  'panelTitle.inactiveForeground': ui.muted,
  'panelTitle.border': ui.line,
  'panelTitleBadge.background': brand.violet,
  'panelTitleBadge.foreground': brand.ink,
  'panelInput.border': ui.line,
  'panelSection.border': ui.line,
  'panelSectionHeader.background': ui.card,
  'panelSectionHeader.border': ui.line,
  'panelStickyScroll.background': ui.card,
  'panelStickyScroll.border': ui.line,
  'terminal.background': ui.card,
  'terminal.foreground': ui.text,
  'terminal.border': ui.line,
  'terminal.selectionBackground': a(brand.violet, 0.3),
  'terminal.inactiveSelectionBackground': a(brand.violet, 0.15),
  'terminal.findMatchBackground': a(brand.warn, 0.4),
  'terminal.findMatchHighlightBackground': a(brand.warn, 0.18),
  'terminal.tab.activeBorder': brand.violet,
  'terminal.dropBackground': a(brand.violet, 0.14),
  'terminalCursor.foreground': brand.orchid,
  'terminalCursor.background': brand.ink,
  'terminalCommandDecoration.defaultBackground': a(ui.bright, 0.25),
  'terminalCommandDecoration.successBackground': brand.keep,
  'terminalCommandDecoration.errorBackground': brand.undo,
  'terminalOverviewRuler.cursorForeground': a(brand.orchid, 0.6),
  'terminalStickyScroll.background': ui.card,
  'terminalStickyScrollHover.background': ui.raised,
  'terminal.ansiBlack': ui.lineStrong,
  'terminal.ansiRed': brand.undo,
  'terminal.ansiGreen': brand.keep,
  'terminal.ansiYellow': brand.warn,
  'terminal.ansiBlue': brand.violet,
  'terminal.ansiMagenta': brand.orchid,
  'terminal.ansiCyan': '#5BC4E6',
  'terminal.ansiWhite': ui.text,
  'terminal.ansiBrightBlack': syntax.comment,
  'terminal.ansiBrightRed': syntax.tag,
  'terminal.ansiBrightGreen': syntax.string,
  'terminal.ansiBrightYellow': syntax.number,
  'terminal.ansiBrightBlue': '#A3AEFF',
  'terminal.ansiBrightMagenta': syntax.keyword,
  'terminal.ansiBrightCyan': syntax.type,
  'terminal.ansiBrightWhite': ui.bright,
  'ports.iconRunningProcessForeground': brand.keep,

  // ---- status bar
  'statusBar.background': ui.window,
  'statusBar.foreground': ui.muted,
  'statusBar.border': none,
  'statusBar.focusBorder': brand.violet,
  'statusBar.noFolderBackground': ui.window,
  'statusBar.noFolderForeground': ui.muted,
  'statusBar.noFolderBorder': none,
  'statusBar.debuggingBackground': brand.orchid,
  'statusBar.debuggingForeground': brand.ink,
  'statusBar.debuggingBorder': none,
  'statusBarItem.hoverBackground': a(ui.bright, 0.08),
  'statusBarItem.hoverForeground': ui.bright,
  'statusBarItem.activeBackground': a(ui.bright, 0.12),
  'statusBarItem.focusBorder': brand.violet,
  'statusBarItem.compactHoverBackground': a(ui.bright, 0.12),
  'statusBarItem.prominentBackground': a(ui.bright, 0.08),
  'statusBarItem.prominentForeground': ui.bright,
  'statusBarItem.prominentHoverBackground': a(ui.bright, 0.12),
  'statusBarItem.remoteBackground': none,
  'statusBarItem.remoteForeground': ui.muted,
  'statusBarItem.remoteHoverBackground': a(ui.bright, 0.08),
  'statusBarItem.remoteHoverForeground': ui.bright,
  'statusBarItem.errorBackground': a(brand.undo, 0.2),
  'statusBarItem.errorForeground': brand.undo,
  'statusBarItem.errorHoverBackground': a(brand.undo, 0.3),
  'statusBarItem.warningBackground': a(brand.warn, 0.2),
  'statusBarItem.warningForeground': brand.warn,
  'statusBarItem.warningHoverBackground': a(brand.warn, 0.3),
  'statusBarItem.offlineBackground': a(brand.undo, 0.2),
  'statusBarItem.offlineForeground': brand.undo,

  // ---- inputs and controls (fields are inset in Ink)
  'input.background': ui.field,
  'input.foreground': ui.text,
  'input.border': ui.line,
  'input.placeholderForeground': ui.faint,
  'inputOption.activeBackground': a(brand.violet, 0.25),
  'inputOption.activeBorder': none,
  'inputOption.activeForeground': ui.bright,
  'inputOption.hoverBackground': a(ui.bright, 0.08),
  'inputValidation.errorBackground': '#2A1A20',
  'inputValidation.errorBorder': brand.undo,
  'inputValidation.infoBackground': '#1C2036',
  'inputValidation.infoBorder': brand.violet,
  'inputValidation.warningBackground': '#2A2217',
  'inputValidation.warningBorder': brand.warn,
  'dropdown.background': ui.field,
  'dropdown.listBackground': ui.raised,
  'dropdown.border': ui.line,
  'dropdown.foreground': ui.text,
  'button.background': brand.violet,
  'button.foreground': brand.ink,
  'button.hoverBackground': brand.violetHover,
  'button.border': none,
  'button.separator': a(brand.ink, 0.4),
  'button.secondaryBackground': ui.raised,
  'button.secondaryForeground': ui.bright,
  'button.secondaryHoverBackground': ui.raisedHover,
  'checkbox.background': ui.field,
  'checkbox.foreground': ui.bright,
  'checkbox.border': ui.lineStrong,
  'checkbox.selectBackground': ui.raised,
  'checkbox.selectBorder': brand.violet,
  'radio.activeBackground': a(brand.violet, 0.25),
  'radio.activeBorder': brand.violet,
  'radio.activeForeground': ui.bright,
  'radio.inactiveBorder': ui.lineStrong,
  'radio.inactiveHoverBackground': a(ui.bright, 0.06),
  'keybindingLabel.background': a(ui.bright, 0.06),
  'keybindingLabel.foreground': ui.text,
  'keybindingLabel.border': ui.line,
  'keybindingLabel.bottomBorder': ui.lineStrong,
  'scrollbar.shadow': a('#000000', 0.4),
  'scrollbarSlider.background': a(ui.bright, 0.1),
  'scrollbarSlider.hoverBackground': a(ui.bright, 0.16),
  'scrollbarSlider.activeBackground': a(ui.bright, 0.22),

  // ---- overlays
  'quickInput.background': ui.raised,
  'quickInput.foreground': ui.text,
  'quickInputTitle.background': a(ui.bright, 0.04),
  'quickInputList.focusBackground': a(brand.violet, 0.22),
  'quickInputList.focusForeground': ui.bright,
  'quickInputList.focusIconForeground': ui.bright,
  'pickerGroup.border': ui.line,
  'pickerGroup.foreground': brand.violetHover,
  'notifications.background': ui.raised,
  'notifications.foreground': ui.text,
  'notifications.border': ui.line,
  'notificationCenter.border': ui.line,
  'notificationCenterHeader.background': ui.raised,
  'notificationCenterHeader.foreground': ui.bright,
  'notificationToast.border': ui.line,
  'notificationLink.foreground': brand.violetHover,
  'notificationsErrorIcon.foreground': brand.undo,
  'notificationsWarningIcon.foreground': brand.warn,
  'notificationsInfoIcon.foreground': brand.violet,
  'banner.background': ui.raised,
  'banner.foreground': ui.text,
  'banner.iconForeground': brand.violet,
  'debugToolBar.background': ui.raised,
  'debugToolBar.border': ui.line,

  // ---- minimap (off by default in Klammr)
  'minimap.background': ui.card,
  'minimap.selectionHighlight': a(brand.violet, 0.4),
  'minimap.findMatchHighlight': a(brand.warn, 0.6),
  'minimap.errorHighlight': a(brand.undo, 0.8),
  'minimap.warningHighlight': a(brand.warn, 0.8),
  'minimap.selectionOccurrenceHighlight': a(ui.bright, 0.25),
  'minimapSlider.background': a(ui.bright, 0.06),
  'minimapSlider.hoverBackground': a(ui.bright, 0.1),
  'minimapSlider.activeBackground': a(ui.bright, 0.14),
  'minimapGutter.addedBackground': brand.keep,
  'minimapGutter.modifiedBackground': brand.violet,
  'minimapGutter.deletedBackground': brand.undo,

  // ---- diff and merge (Keep / Undo)
  'diffEditor.insertedTextBackground': a(brand.keep, 0.18),
  'diffEditor.removedTextBackground': a(brand.undo, 0.18),
  'diffEditor.insertedLineBackground': a(brand.keep, 0.08),
  'diffEditor.removedLineBackground': a(brand.undo, 0.08),
  'diffEditor.diagonalFill': a(ui.bright, 0.08),
  'diffEditor.border': ui.line,
  'diffEditor.unchangedRegionBackground': ui.window,
  'diffEditor.unchangedRegionForeground': ui.muted,
  'diffEditor.unchangedRegionShadow': a('#000000', 0.4),
  'diffEditor.unchangedCodeBackground': a(ui.bright, 0.04),
  'diffEditor.move.border': a(ui.muted, 0.5),
  'diffEditor.moveActive.border': brand.warn,
  'diffEditorGutter.insertedLineBackground': a(brand.keep, 0.12),
  'diffEditorGutter.removedLineBackground': a(brand.undo, 0.12),
  'diffEditorOverview.insertedForeground': a(brand.keep, 0.6),
  'diffEditorOverview.removedForeground': a(brand.undo, 0.6),
  'multiDiffEditor.headerBackground': ui.raised,
  'multiDiffEditor.background': ui.card,
  'multiDiffEditor.border': ui.line,
  'merge.currentHeaderBackground': a(brand.keep, 0.35),
  'merge.currentContentBackground': a(brand.keep, 0.12),
  'merge.incomingHeaderBackground': a(brand.violet, 0.35),
  'merge.incomingContentBackground': a(brand.violet, 0.12),
  'merge.commonHeaderBackground': a(ui.bright, 0.2),
  'merge.commonContentBackground': a(ui.bright, 0.06),
  'mergeEditor.change.background': a(brand.violet, 0.12),
  'mergeEditor.change.word.background': a(brand.violet, 0.2),
  'mergeEditor.conflict.unhandledUnfocused.border': a(brand.warn, 0.5),
  'mergeEditor.conflict.unhandledFocused.border': brand.warn,
  'mergeEditor.conflict.handledUnfocused.border': a(brand.keep, 0.3),
  'mergeEditor.conflict.handledFocused.border': a(brand.keep, 0.7),

  // ---- source control
  'gitDecoration.addedResourceForeground': brand.keep,
  'gitDecoration.modifiedResourceForeground': brand.warn,
  'gitDecoration.deletedResourceForeground': brand.undo,
  'gitDecoration.renamedResourceForeground': brand.keep,
  'gitDecoration.stageModifiedResourceForeground': brand.warn,
  'gitDecoration.stageDeletedResourceForeground': brand.undo,
  'gitDecoration.untrackedResourceForeground': brand.keep,
  'gitDecoration.ignoredResourceForeground': ui.faint,
  'gitDecoration.conflictingResourceForeground': brand.undo,
  'gitDecoration.submoduleResourceForeground': brand.violetHover,
  'scmGraph.historyItemRefColor': brand.violet,
  'scmGraph.historyItemRemoteRefColor': brand.orchid,
  'scmGraph.historyItemBaseRefColor': brand.warn,
  'scmGraph.historyItemHoverDefaultLabelForeground': ui.bright,
  'scmGraph.foreground1': brand.violet,
  'scmGraph.foreground2': brand.orchid,
  'scmGraph.foreground3': brand.keep,
  'scmGraph.foreground4': brand.warn,
  'scmGraph.foreground5': '#5BC4E6',

  // ---- debugging
  'debugExceptionWidget.background': '#2A1A20',
  'debugExceptionWidget.border': brand.undo,
  'debugIcon.breakpointForeground': brand.undo,
  'debugIcon.breakpointDisabledForeground': ui.faint,
  'debugIcon.breakpointUnverifiedForeground': ui.muted,
  'debugIcon.breakpointCurrentStackframeForeground': brand.warn,
  'debugIcon.breakpointStackframeForeground': brand.keep,
  'debugIcon.startForeground': brand.keep,
  'debugIcon.pauseForeground': brand.violet,
  'debugIcon.stopForeground': brand.undo,
  'debugIcon.disconnectForeground': brand.undo,
  'debugIcon.restartForeground': brand.keep,
  'debugIcon.stepOverForeground': brand.violet,
  'debugIcon.stepIntoForeground': brand.violet,
  'debugIcon.stepOutForeground': brand.violet,
  'debugIcon.stepBackForeground': brand.violet,
  'debugIcon.continueForeground': brand.violet,
  'debugConsole.infoForeground': brand.violetHover,
  'debugConsole.warningForeground': brand.warn,
  'debugConsole.errorForeground': brand.undo,
  'debugConsole.sourceForeground': ui.text,
  'debugConsoleInputIcon.foreground': brand.violet,
  'debugTokenExpression.name': syntax.keyword,
  'debugTokenExpression.type': syntax.type,
  'debugTokenExpression.value': a(ui.text, 0.8),
  'debugTokenExpression.string': syntax.string,
  'debugTokenExpression.boolean': syntax.number,
  'debugTokenExpression.number': syntax.number,
  'debugTokenExpression.error': brand.undo,
  'debugView.exceptionLabelBackground': a(brand.undo, 0.3),
  'debugView.stateLabelBackground': a(ui.bright, 0.1),
  'debugView.stateLabelForeground': ui.text,
  'debugView.valueChangedHighlight': brand.violet,
  'editor.stackFrameHighlightBackground': a(brand.warn, 0.12),
  'editor.focusedStackFrameHighlightBackground': a(brand.keep, 0.1),

  // ---- settings, extensions, welcome
  'settings.headerForeground': ui.bright,
  'settings.modifiedItemIndicator': brand.violet,
  'settings.dropdownBackground': ui.field,
  'settings.dropdownForeground': ui.text,
  'settings.dropdownBorder': ui.line,
  'settings.dropdownListBorder': ui.line,
  'settings.checkboxBackground': ui.field,
  'settings.checkboxForeground': ui.bright,
  'settings.checkboxBorder': ui.lineStrong,
  'settings.textInputBackground': ui.field,
  'settings.textInputForeground': ui.text,
  'settings.textInputBorder': ui.line,
  'settings.numberInputBackground': ui.field,
  'settings.numberInputForeground': ui.text,
  'settings.numberInputBorder': ui.line,
  'settings.focusedRowBackground': a(ui.bright, 0.03),
  'settings.focusedRowBorder': none,
  'settings.rowHoverBackground': a(ui.bright, 0.02),
  'settings.sashBorder': ui.line,
  'settings.headerBorder': ui.line,
  'extensionButton.prominentBackground': brand.violet,
  'extensionButton.prominentForeground': brand.ink,
  'extensionButton.prominentHoverBackground': brand.violetHover,
  'extensionButton.background': brand.violet,
  'extensionButton.foreground': brand.ink,
  'extensionButton.hoverBackground': brand.violetHover,
  'extensionButton.separator': a(brand.ink, 0.4),
  'extensionBadge.remoteBackground': brand.violet,
  'extensionBadge.remoteForeground': brand.ink,
  'extensionIcon.starForeground': brand.warn,
  'extensionIcon.verifiedForeground': brand.violet,
  'extensionIcon.preReleaseForeground': brand.keep,
  'extensionIcon.sponsorForeground': brand.orchid,
  'welcomePage.background': ui.card,
  'welcomePage.tileBackground': ui.raised,
  'welcomePage.tileHoverBackground': ui.raisedHover,
  'welcomePage.tileBorder': ui.line,
  'welcomePage.progress.background': ui.field,
  'welcomePage.progress.foreground': brand.violet,
  'walkThrough.embeddedEditorBackground': ui.field,
  'walkthrough.stepTitle.foreground': ui.bright,
  'problemsErrorIcon.foreground': brand.undo,
  'problemsWarningIcon.foreground': brand.warn,
  'problemsInfoIcon.foreground': brand.violet,
  'profileBadge.background': ui.raisedHover,
  'profileBadge.foreground': ui.bright,

  // ---- symbols, notebooks, charts, testing
  'symbolIcon.classForeground': syntax.type,
  'symbolIcon.interfaceForeground': syntax.type,
  'symbolIcon.structForeground': syntax.type,
  'symbolIcon.typeParameterForeground': syntax.type,
  'symbolIcon.moduleForeground': syntax.type,
  'symbolIcon.namespaceForeground': syntax.type,
  'symbolIcon.packageForeground': syntax.type,
  'symbolIcon.functionForeground': syntax.func,
  'symbolIcon.methodForeground': syntax.func,
  'symbolIcon.constructorForeground': syntax.keyword,
  'symbolIcon.eventForeground': syntax.number,
  'symbolIcon.enumeratorForeground': syntax.number,
  'symbolIcon.enumeratorMemberForeground': syntax.number,
  'symbolIcon.constantForeground': syntax.number,
  'symbolIcon.numberForeground': syntax.number,
  'symbolIcon.booleanForeground': syntax.number,
  'symbolIcon.stringForeground': syntax.string,
  'symbolIcon.keyForeground': syntax.func,
  'symbolIcon.keywordForeground': syntax.keyword,
  'symbolIcon.operatorForeground': ui.muted,
  'symbolIcon.variableForeground': ui.text,
  'symbolIcon.fieldForeground': ui.text,
  'symbolIcon.propertyForeground': ui.text,
  'symbolIcon.fileForeground': ui.muted,
  'symbolIcon.folderForeground': ui.muted,
  'symbolIcon.referenceForeground': ui.muted,
  'symbolIcon.snippetForeground': ui.muted,
  'symbolIcon.textForeground': ui.muted,
  'symbolIcon.unitForeground': ui.muted,
  'symbolIcon.colorForeground': ui.muted,
  'symbolIcon.arrayForeground': ui.muted,
  'symbolIcon.objectForeground': ui.muted,
  'symbolIcon.nullForeground': ui.muted,
  'notebook.cellBorderColor': ui.line,
  'notebook.cellEditorBackground': ui.field,
  'notebook.focusedCellBorder': brand.violet,
  'notebook.focusedEditorBorder': brand.violet,
  'notebook.inactiveFocusedCellBorder': ui.line,
  'notebook.selectedCellBackground': a(ui.bright, 0.03),
  'notebook.selectedCellBorder': ui.line,
  'notebook.cellStatusBarItemHoverBackground': a(ui.bright, 0.1),
  'notebook.cellToolbarSeparator': ui.line,
  'notebook.editorBackground': ui.card,
  'notebookStatusSuccessIcon.foreground': brand.keep,
  'notebookStatusErrorIcon.foreground': brand.undo,
  'notebookStatusRunningIcon.foreground': ui.text,
  'charts.foreground': ui.text,
  'charts.lines': a(ui.text, 0.5),
  'charts.red': brand.undo,
  'charts.blue': brand.violet,
  'charts.yellow': brand.warn,
  'charts.orange': syntax.number,
  'charts.green': brand.keep,
  'charts.purple': brand.orchid,
  'testing.iconFailed': brand.undo,
  'testing.iconErrored': brand.undo,
  'testing.iconPassed': brand.keep,
  'testing.runAction': brand.keep,
  'testing.iconQueued': brand.warn,
  'testing.iconUnset': ui.faint,
  'testing.iconSkipped': ui.faint,
  'testing.peekBorder': brand.undo,
  'testing.peekHeaderBackground': a(brand.undo, 0.1),
  'testing.coveredBackground': a(brand.keep, 0.12),
  'testing.uncoveredBackground': a(brand.undo, 0.12),
  'inlineEdit.gutterIndicator.primaryBackground': brand.violet,
  'inlineEdit.gutterIndicator.primaryForeground': brand.ink,
};

// ---- TextMate scopes ---------------------------------------------------------------------------
const rule = (scope, foreground, fontStyle) => ({ scope, settings: { ...(foreground ? { foreground } : {}), ...(fontStyle ? { fontStyle } : {}) } });

const tokenColors = [
  rule(['comment', 'punctuation.definition.comment', 'string.comment', 'comment.block.documentation', 'comment.line.documentation'], syntax.comment, 'italic'),
  rule(['storage.type.class.jsdoc', 'storage.type.class.doxygen', 'keyword.other.phpdoc', 'punctuation.definition.block.tag.jsdoc'], syntax.keyword, 'italic'),
  rule(['entity.name.type.instance.jsdoc', 'variable.other.jsdoc'], syntax.text, 'italic'),

  rule(['keyword', 'storage', 'storage.type', 'storage.modifier', 'keyword.control', 'keyword.other', 'keyword.operator.new', 'keyword.operator.expression', 'keyword.operator.cast', 'keyword.operator.sizeof', 'keyword.operator.instanceof', 'keyword.operator.typeof', 'keyword.operator.delete', 'keyword.operator.wordlike', 'keyword.operator.logical.python', 'keyword.operator.noexcept', 'variable.language', 'support.type.object.module', 'punctuation.definition.template-expression', 'punctuation.section.embedded'], syntax.keyword),
  rule(['keyword.operator', 'keyword.operator.assignment', 'keyword.operator.arithmetic', 'keyword.operator.comparison', 'keyword.operator.relational', 'keyword.operator.logical', 'keyword.operator.ternary', 'keyword.operator.spread', 'keyword.operator.rest', 'keyword.operator.optional', 'storage.type.function.arrow'], syntax.operator),
  rule(['punctuation', 'meta.brace', 'punctuation.definition.tag', 'punctuation.separator', 'punctuation.terminator', 'punctuation.accessor'], syntax.operator),

  rule(['string', 'string.quoted', 'string.template', 'punctuation.definition.string', 'string.unquoted.plain.out.yaml', 'string.unquoted.plain.in.yaml', 'markup.inline.raw.string.markdown'], syntax.string),
  rule(['meta.template.expression', 'meta.embedded', 'source.groovy.embedded', 'meta.interpolation'], syntax.text),
  rule(['string.regexp', 'constant.other.character-class.regexp', 'constant.character.character-class.regexp', 'constant.character.set.regexp', 'punctuation.definition.group.regexp', 'punctuation.definition.character-class.regexp', 'keyword.operator.or.regexp', 'keyword.control.anchor.regexp'], syntax.tag),
  rule(['constant.character.escape', 'constant.character.format.placeholder', 'constant.other.placeholder', 'keyword.operator.quantifier.regexp'], syntax.number),

  rule(['constant.numeric', 'constant.language', 'constant.character', 'constant.other.option', 'support.constant', 'variable.other.enummember', 'keyword.other.unit', 'keyword.operator.plus.exponent', 'keyword.operator.minus.exponent', 'constant.other.color', 'constant.other.symbol.ruby'], syntax.number),
  rule(['meta.decorator', 'entity.name.function.decorator', 'punctuation.decorator', 'storage.type.annotation', 'punctuation.definition.annotation', 'meta.attribute.rust', 'entity.name.function.preprocessor', 'meta.preprocessor'], syntax.number),

  rule(['entity.name.function', 'support.function', 'meta.function-call.generic', 'variable.function', 'entity.name.method', 'entity.name.operator.custom-literal', 'support.function.builtin.shell', 'entity.name.command.shell', 'support.constant.handlebars'], syntax.func),
  rule(['entity.name.type', 'entity.name.class', 'entity.name.struct', 'entity.name.enum', 'entity.name.interface', 'entity.name.trait', 'entity.name.namespace', 'entity.name.module', 'entity.name.scope-resolution', 'entity.other.inherited-class', 'entity.other.attribute', 'support.type', 'support.class', 'support.other.namespace', 'storage.type.primitive', 'storage.type.built-in', 'storage.type.numeric.go', 'storage.type.byte.go', 'storage.type.boolean.go', 'storage.type.string.go', 'storage.type.uintptr.go', 'storage.type.error.go', 'storage.type.rune.go', 'storage.type.cs', 'storage.type.java', 'storage.type.generic.java', 'storage.type.object.array.java', 'storage.type.primitive.array.java', 'meta.type.cast.expr', 'meta.type.new.expr', 'support.constant.math', 'support.constant.dom', 'support.constant.json', 'support.class.component', 'variable.other.normal.shell', 'variable.other.special.shell', 'variable.other.positional.shell', 'punctuation.definition.variable.shell'], syntax.type),

  rule(['variable', 'variable.other', 'variable.other.readwrite', 'variable.other.constant', 'variable.other.object', 'variable.other.property', 'variable.other.object.property', 'variable.parameter', 'meta.definition.variable.name', 'meta.object-literal.key', 'support.variable', 'support.variable.property', 'entity.name.variable', 'entity.name.label', 'variable.legacy.builtin.python'], syntax.text),

  rule(['entity.name.tag', 'meta.tag.sgml', 'markup.deleted.git_gutter'], syntax.tag),
  rule(['entity.other.attribute-name', 'entity.other.attribute-name.class.css', 'entity.other.attribute-name.id.css', 'entity.other.attribute-name.pseudo-class.css', 'entity.other.attribute-name.pseudo-element.css', 'entity.other.attribute-name.scss', 'entity.other.attribute-name.parent-selector.css'], syntax.number),
  rule(['entity.name.tag.css', 'entity.name.tag.less', 'entity.name.tag.scss'], syntax.tag),
  rule(['support.type.property-name', 'support.type.vendored.property-name', 'support.type.property-name.json', 'support.type.property-name.toml', 'keyword.key.toml', 'entity.name.tag.yaml', 'meta.mapping.key', 'source.css variable', 'variable.css', 'variable.scss', 'support.function.git-rebase'], syntax.func),
  rule(['support.constant.property-value', 'support.constant.font-name', 'support.constant.media-type', 'support.constant.media', 'constant.other.rgb-value', 'support.constant.color', 'constant.sha.git-rebase'], syntax.number),

  rule(['markup.heading', 'entity.name.section', 'punctuation.definition.heading.markdown', 'markup.heading.setext'], brand.violetHover, 'bold'),
  rule(['markup.bold', 'punctuation.definition.bold.markdown'], ui.bright, 'bold'),
  rule(['markup.italic', 'punctuation.definition.italic.markdown'], syntax.text, 'italic'),
  rule('markup.strikethrough', undefined, 'strikethrough'),
  rule('markup.underline', undefined, 'underline'),
  rule(['markup.inline.raw', 'markup.raw.block', 'markup.fenced_code.block'], syntax.string),
  rule(['punctuation.definition.markdown', 'fenced_code.block.language'], ui.muted),
  rule(['markup.quote', 'punctuation.definition.quote.begin.markdown'], ui.muted, 'italic'),
  rule(['markup.underline.link', 'string.other.link', 'constant.other.reference.link.markdown', 'markup.underline.link.image'], brand.violetHover),
  rule(['punctuation.definition.list.begin.markdown', 'beginning.punctuation.definition.list.markdown', 'beginning.punctuation.definition.quote.markdown', 'meta.separator.markdown'], syntax.keyword),
  rule(['markup.inserted', 'markup.inserted.diff', 'punctuation.definition.inserted.diff'], brand.keep),
  rule(['markup.deleted', 'markup.deleted.diff', 'punctuation.definition.deleted.diff'], brand.undo),
  rule(['markup.changed', 'markup.changed.diff', 'punctuation.definition.changed.diff'], brand.warn),
  rule(['meta.diff.header', 'meta.diff.range', 'meta.diff.header.from-file', 'meta.diff.header.to-file'], brand.violetHover),

  rule(['invalid', 'invalid.illegal'], brand.undo),
  rule('invalid.deprecated', brand.warn, 'strikethrough'),
];

const semanticTokenColors = {
  namespace: syntax.type,
  class: syntax.type,
  interface: syntax.type,
  enum: syntax.type,
  struct: syntax.type,
  type: syntax.type,
  typeParameter: syntax.type,
  'class.defaultLibrary': syntax.type,
  function: syntax.func,
  method: syntax.func,
  macro: syntax.func,
  'function.defaultLibrary': syntax.func,
  'method.defaultLibrary': syntax.func,
  variable: syntax.text,
  'variable.readonly': syntax.text,
  'variable.defaultLibrary': syntax.text,
  parameter: syntax.text,
  property: syntax.text,
  'property.readonly': syntax.text,
  enumMember: syntax.number,
  decorator: syntax.number,
  keyword: syntax.keyword,
  selfKeyword: syntax.keyword,
  selfParameter: syntax.keyword,
  newOperator: syntax.keyword,
  operator: syntax.operator,
  number: syntax.number,
  numberLiteral: syntax.number,
  boolean: syntax.number,
  string: syntax.string,
  stringLiteral: syntax.string,
  regexp: syntax.tag,
  customLiteral: syntax.func,
  label: syntax.text,
  comment: { foreground: syntax.comment, italic: true },
};

const theme = {
  $schema: 'vscode://schemas/color-theme',
  name: 'Klammr Dark',
  type: 'dark',
  semanticHighlighting: true,
  colors,
  tokenColors,
  semanticTokenColors,
};

const json = `${JSON.stringify(theme, null, 2)}\n`;
if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== json) {
    console.error(`${path.relative(ROOT, OUT)} is out of date — run: npm run theme`);
    process.exit(1);
  }
  console.log(`${path.relative(ROOT, OUT)} is up to date`);
} else {
  fs.writeFileSync(OUT, json);
  console.log(`wrote ${path.relative(ROOT, OUT)} (${Object.keys(colors).length} colors, ${tokenColors.length} token rules)`);
}
